// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import { RemovalPolicy } from 'aws-cdk-lib';
import { Table, AttributeType } from 'aws-cdk-lib/aws-dynamodb';
import { Function } from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export class UserTable extends Table {
  constructor(scope: Construct, id: string) {
    super(scope, id, {
      partitionKey: {
        name: 'username',
        type: AttributeType.STRING,
      },
      sortKey: {
        name: 'code',
        type: AttributeType.NUMBER,
      },
      removalPolicy: RemovalPolicy.DESTROY,
    });
  }

  public bind(handler: Function, grantType: string) {
    handler.addEnvironment('USER_TABLE_NAME', this.tableName);
    if (grantType.toLowerCase() === 'write') {
      this.grantWriteData(handler);
    }
    if (grantType.toLowerCase() === 'read') {
      this.grantReadData(handler);
    }
    if (grantType.toLowerCase() === 'readwrite') {
      this.grantReadWriteData(handler);
    }
  }
};