// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import {
  DynamoDBClient,
  PutItemCommand, PutItemCommandInput,
  UpdateItemCommand, UpdateItemCommandInput,
  GetItemCommand, GetItemCommandInput,
  DeleteItemCommand, DeleteItemCommandInput,
} from '@aws-sdk/client-dynamodb';
import { marshall } from '@aws-sdk/util-dynamodb';
import { User } from './model';

export class UserClient {
  readonly client = new DynamoDBClient({ region: process.env.AWS_REGION });

  public async getItem(partitionKey: string, sortKey: number) {
    let keyObj: { [key: string]: any } = {};
    keyObj.username = partitionKey;
    keyObj.code = sortKey;
    const input: GetItemCommandInput = {
      TableName: process.env.USER_TABLE_NAME,
      Key: marshall(keyObj),
    };
    return this.client.send(new GetItemCommand(input));
  }

  public async deleteItem(partitionKey: string, sortKey: number) {
    let keyObj: { [key: string]: any } = {};
    keyObj.username = partitionKey;
    keyObj.code = sortKey;
    const input: DeleteItemCommandInput = {
      TableName: process.env.USER_TABLE_NAME,
      Key: marshall(keyObj),
    };
    return this.client.send(new DeleteItemCommand(input));
  }
  public async putItem(item: User) {
    const input: PutItemCommandInput = {
      TableName: process.env.USER_TABLE_NAME,
      Item: marshall(item),
    };
    return this.client.send(new PutItemCommand(input));
  }

  public async updateItem(partitionKey: string, item: User) {
    let expAttrVal: { [key: string]: any } = {};
    let upExp = 'set ';
    let expAttrNames: { [key: string]: string } = {};
    if (item.name !== null && item.name !== undefined) {
      expAttrVal[':name'] = item.name;
      upExp = upExp + '#name = :name,';
      expAttrNames['#name'] = 'name';
    };
    if (item.age !== null && item.age !== undefined) {
      expAttrVal[':age'] = item.age;
      upExp = upExp + '#age = :age,';
      expAttrNames['#age'] = 'age';
    };
    if (item.lastname !== null && item.lastname !== undefined) {
      expAttrVal[':lastname'] = item.lastname;
      upExp = upExp + '#lastname = :lastname,';
      expAttrNames['#lastname'] = 'lastname';
    };
    if (item.phone !== null && item.phone !== undefined) {
      expAttrVal[':phone'] = item.phone;
      upExp = upExp + '#phone = :phone,';
      expAttrNames['#phone'] = 'phone';
    };
    if (item.address !== null && item.address !== undefined) {
      expAttrVal[':address'] = item.address;
      upExp = upExp + '#address = :address,';
      expAttrNames['#address'] = 'address';
    };
    upExp = upExp.slice(0, -1);
    let keyObj: { [key: string]: any } = {};
    keyObj.username = partitionKey;
    keyObj.code = item.code;
    const input: UpdateItemCommandInput = {
      TableName: process.env.USER_TABLE_NAME,
      Key: marshall(keyObj),
      ExpressionAttributeValues: marshall(expAttrVal),
      UpdateExpression: upExp,
      ExpressionAttributeNames: expAttrNames,
    };
    console.log(input);
    return this.client.send(new UpdateItemCommand(input));
  }

};