// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
export interface User {
  /**
  * **_username_** field is the **partition key**
  *
  * @attribute
  */
  readonly username: string; // key
  /**
  * **_code_** field is the **sort key**
  *
  * @attribute
  */
  readonly code: number; // sort key
  /**
  *
  * @attribute
  */
  readonly name?: string;
  /**
  *
  * @attribute
  */
  readonly age?: number;
  /**
  *
  * @attribute
  */
  readonly lastname?: string;
  /**
  *
  * @attribute
  */
  readonly phone?: string;
  /**
  *
  * @attribute
  */
  readonly address?: string;
};