// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
export interface UserKey {
  /**
  * **_username_** field is the **partition key**
  *
  * @attribute
  */
  readonly username: string; // partition key
  /**
  * **_loginDate_** field is the **sort key**
  *
  * @attribute
  */
  readonly loginDate: string; // sort key
}

export interface User extends UserKey {
  /**
  *
  * @attribute
  */
  readonly name?: string;
  /**
  *
  * @attribute
  */
  readonly age?: number;
  /**
  *
  * @attribute
  */
  readonly lastname?: string;
  /**
  *
  * @attribute
  */
  readonly phone?: string;
  /**
  *
  * @attribute
  */
  readonly address?: string;
}
